image:
  repository: busybox
  pullPolicy: IfNotPresent

securityContext:
  capabilities:
    add:
      [ NET_ADMIN ]

resources:
  limits:
    cpu: 10m
    memory: 16Mi
  requests:
    cpu: 10m
    memory: 16Mi

commands:
  - /bin/ip route add 192.168.40.0/24 via 10.14.80.12
  - /bin/ip route add 192.168.42.0/24 via 10.14.80.12
